version: '3'

services:
  mysql:
      image: mysql:8.0
      container_name: mysql
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        MYSQL_DATABASE: myapp-sql
        MYSQL_USER: myapp-sql
        MYSQL_PASSWORD: 123456
      ports:
        - "33306:3306"  # MySQL 접근 포트
      networks:
        - myappnet

  myfastapi:
    build:
      context: ./myfastapi
      dockerfile: Dockerfile
    container_name: myfastapi
    ports:
      - "8001:8000"
    environment:
      - SQLALCHEMY_DATABASE_URL=mysql+pymysql://myapp-sql:123456@mysql/myapp-sql
    volumes:
      - ./myfastapi:/src  # 로컬 소스 코드 바인딩
    depends_on:
      - mysql
    networks:
      - mynet
      
  myfront:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myfront
    ports:
      - "8002:5173"  # 프론트엔드 접근 포트
    volumes:
      - ./frontend:/src  # 로컬 소스 코드 바인딩
      - /src/node_modules feedback-node:bind # 이미지 빌드 시 생성된 node_modules 폴더는 덮어씌우지 않음
    networks:
      - mynet
    depends_on:
      - myfastapi

  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: myproxy
    ports:
      - "8181:8181"  # Nginx Proxy Manager 웹 UI 포트
      - "80:8080"    # HTTP 트래픽을 위한 포트
      - "443:4443"   # HTTPS 트래픽을 위한 포트
    volumes:
      - /docker/appdata/nginx-proxy-manager:/config:rw  # 설정 데이터 영구 저장소
    networks:
      - mynet
    depends_on:
      - myfastapi
      - myfront

networks:
  mynet:
    driver: bridge

